### PR TITLE
feat: personal insights + model update + deletion of account

### PR DESCRIPTION
**Pull request by Jatewo**
## Description

This is a merged PR of PRs #30, #35, and #36

## Changes

- functionality implemented for personal insights
- personal insights now contains dynamic information about name, total subscribers and average star rating
- shows count of courses with each status
- written tests for the above functionality
- update tests and their snapshots
- added key[i] to Carousel.tsx
- Move course stat functions into helper file
- modifiedAt changed to dateUpdated
- createdAt changed to dateCreated
- Added a "delete account" button with a popup massage.
- Added a simple localStorage.setItem("id", res.data.userInfo.id) in the login page so it is possible to fetch the users id when calling the delete route.

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

## If mobile/frontend pull request, what version of the backend is it stable, and running on? 

Branch: dev

### CODE REVIEW

**Review by MortenMunk — APPROVED** [review]
Code looks mighty fine to me 👍 🥇

**Review by Mafusn — APPROVED** [review]
Looks good.

**Review by sofiiagran — CHANGES_REQUESTED** [review]
DO NOT MERGE, I WILL MAKE A QUICK FIX FOR MY ROUTE

**Review by sofiiagran — APPROVED** [review]
Looks goodie

**Comment by Jatewo** [comment]
Is this ready for merging now?

**Comment by Jatewo** [comment]
@sofiiagran I think you may have forgotten to update a test 😄

**Comment by sofiiagran** [comment]
Now it should be fine:)) @Jatewo

**Pull request merged**
