### PR TITLE
BUG - Institution search

### PR DESCRIPTION
**Pull request by Todua992**
There were made some Hotfixes in the backend Dev, where now the SubDomains are actually Optional. Instead of just crashing and giving errors.

 Since that was fixed, The FrontEnd, was failing when we tried to search Institutions, As it could not understand "Null" Domains. 
 
 I fixed that issue, and now it can. On top of that I improved the overall code quality, to make it more readable and removed the If statments.

`  if (searchTerm === "") return institution;
    const fieldsToCheck = ["institutionName", "domain", "secondaryDomain"];
    return fieldsToCheck.some(
      (field) =>
        institution[field] &&
        institution[field].toLowerCase().includes(searchTerm.toLowerCase())
    );
  });`

### CODE REVIEW

**Review by madsWesth — APPROVED** [review]
Nice 👍 I'm hoping i have time to make the search into a hook and i can include this when I refactor the tables on the admin page

**Review by LazarShockX — APPROVED** [review]
Great job - now fix the tests 🫵

**Comment by Todua992** [comment]
> Great job - now fix the tests 🫵

Magnus is Fixing them.

**Comment by Todua992** [comment]
> Nice 👍 I'm hoping i have time to make the search into a hook and i can include this when I refactor the tables on the admin page

Will be very good Idea. For Now we can keep this, So atleast it can search XD

**Pull request closed without merging**
