### PR TITLE
Navigation Button Bug

### PR DESCRIPTION
**Pull request by MartinJenzen**
## Description

Solving project backlog requirement item [#91]
[Web - Home] As a content creator, I need a header that allows me to navigate back to the main parts of the platform

## Changes

- Notification icon (bell) in the interface header made into a button that now shows a dropdown menu with 3 placeholder notifications for now (not linked to any data source).
- Made "Cancelar edições" button in **/profile** end-point functional (redirects user back to /courses).
- "Deletar conta" button in **/profile** was non-functional before, but now it actually leads user to the account deletion request end-point (**/account_deletion_request**). End-point is now also made accessible for logged-in users.
- Added a return button to **/account_deletion_request** (it now leads back to default page).
- Unobscured the user dropdown menu in the interface header on the **/profile** end-point, by removing the 'relative' CSS-properties of relevant elements.

## Related Issues

None.

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

## Screenshots (if applicable)

- Clickable notification icon (bell) dropdown menu in interface header with placeholder notifications:
notication_icon_with_dropdown_menu

- Return button on **/account_deletion_request** after pressing "Deletar conta" on **/profile**;
image

- User dropdown menu is no longer obscured by expandable menu elements on **/profile**:
image

## If mobile/frontend pull request, what version of the backend is it stable, and running on? 

Branch: main

Commit id: 1f44f2a 

## Notes for Reviewers

None.

### CODE REVIEW

**Comment by magnusklundgren** [comment]
Notification button(bell) does not collapse when clicked after the menu is dropped down. Seems counter-intuitive.

**Comment by magnusklundgren** [comment]
Fix notification menu to be collapsible and fix merge conflicts then it's good to go.
Consider if there needs to be tests on the frontend for deleting an account.

**Comment by MartinJenzen** [comment]
@magnusklundgren 
Minor issue with dropdown menu not collapsing when pressed again is ignored, because the behavior is reflecting the already existing user account dropdown menu, where dropdown menu is not collapsing either when pressed again. A new PBI could potentially fix this minor issue in the future.

Merge conflicts have been resolved.

**Comment by magnusklundgren** [comment]
👍

**Pull request merged**
