### PR TITLE
Save as draft popup dialogue. Deadlocked group.

### PR DESCRIPTION
**Pull request by magnusklundgren**
## Description

Added the proper popup and dialogue according to figma when saving as draft. Also implemented the correct logic in order to save this on the backend.

## Changes

Added Popup component with styling.
Dynamically changes the dialogue message and functionality depending on which button is clicked in the course creation.

## Related Issues

https://github.com/orgs/Educado-App/projects/14/views/12?pane=issue&itemId=80632799

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [] Reviewers have been assigned to the pull request.

## Screenshots (if applicable)
image
figma reference: https://www.figma.com/design/BCEVQYvMDrcBE9qqehr9HL/Mobile-Education-UI?node-id=5217-2723&node-type=frame&t=5maS7AeGlSrEQ4hl-0

### CODE REVIEW

**Review by Lowkee1g — CHANGES_REQUESTED** [review]
Might have crossover with Group 1 with Toast

**Comment by magnusklundgren** [comment]
TODO: Resolve conflicts

**Comment by Laskiri** [comment]
I've resolved conflicts with dev and also integrated changes with other popup component group and the notification system, so it should be good to merge, after the notification/system has been merged into dev. I'm still waiting for them to fix their current PR to merge into dev instead of main.

**Review by MartinJenzen — APPROVED** [review]
Beautiful! \***chef's kiss**\* 
Mucho bueno, boys 👍

**Pull request merged**
