### PR TITLE
Update Linting.yml

### PR DESCRIPTION
**Pull request by magnusklundgren**
Updated Linting.yml so it runs Eslint correctly and also implemented a prettier command in package.json.
Check fails, but only because we have a ton of linting errors, so should be all good. Maybe people will do something about it now.

### CODE REVIEW

**Comment by madsWesth** [comment]
I have merged the staging to main, maybe now the deployment will happen on the staging branch. Maybe we could do a small pr to staging that adds a single console.log for testing or should we just leave it for now?

Also it looks like we use prettier on the CI/CD so maybe we should push for people to use that while developing? We could do this:https://github.com/Educado-App/educado-frontend/pull/158 for prettier too and update the READMEs

**Comment by magnusklundgren** [comment]
> I have merged the staging to main, maybe now the deployment will happen on the staging branch. Maybe we could do a small pr to staging that adds a single console.log for testing or should we just leave it for now?

I talked to Bence about deploying on staging. It is handled on Google Cloud Platform and whenever there has been an attempt to deploy on staging it just does weird stuff. Changing the github actions workflow does not seem to do anything to actually deploy

**Comment by madsWesth** [comment]
> > I have merged the staging to main, maybe now the deployment will happen on the staging branch. Maybe we could do a small pr to staging that adds a single console.log for testing or should we just leave it for now?
> 
> I talked to Bence about deploying on staging. It is handled on Google Cloud Platform and whenever there has been an attempt to deploy on staging it just does weird stuff. Changing the github actions workflow does not seem to do anything to actually deploy

Should we remove the deploy GitHub action then? So other people don't get confused by it as well

**Comment by magnusklundgren** [comment]
Think we just leave the github CD as is and only change CI like this change.

**Pull request merged**
